apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: burst-webhook-secret
      namespace: monitoring
      labels:
        app: burst-webhook
    type: Opaque

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: burst-webhook
      namespace: monitoring
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: burst-webhook
      template:
        metadata:
          labels:
            app: burst-webhook
        spec:
          containers:
            - name: burst-webhook
              image: smeetnagda/burst-webhook:latest
              ports:
                - containerPort: 3000
              envFrom:
                - secretRef:
                    name: burst-webhook-secret
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                readOnlyRootFilesystem: true

  - apiVersion: v1
    kind: Service
    metadata:
      name: burst-webhook
      namespace: monitoring
    spec:
      type: NodePort
      selector:
        app: burst-webhook
      ports:
        - name: http
          port: 80
          targetPort: 3000
          nodePort: 30999
