apiVersion: v1
kind: Secret
metadata:
  name: burst-webhook-secret
  namespace: monitoring
  labels:
    app: burst-webhook
type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: burst-webhook
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burst-webhook
  template:
    metadata:
      labels:
        app: burst-webhook
    spec:
      containers:
        - name: burst-webhook
          # Replace this image with the actual location of your built Docker image.
          image: smeetnagda/burst-webhook:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: burst-webhook-secret

---
apiVersion: v1
kind: Service
metadata:
  name: burst-webhook
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: burst-webhook
  ports:
    - name: http
      port: 80
      targetPort: 3000
      # Choose a nodePort that is free on your minikube host. This example uses
      # 30999, but any free port in the NodePort range (30000‑32767) will work.
      nodePort: 30999
